import type { DataState } from "./types";

// Seed data — realistic cacao / sweetener / emulsifier suppliers so the hub
// is immediately explorable. Used in local mode and as a reset target.
export function seedData(): DataState {
  const day = (offset: number) => {
    const d = new Date();
    d.setDate(d.getDate() - offset);
    return d.toISOString();
  };

  return {
    suppliers: [
      {
        id: "sup_barry",
        company: "Barry Callebaut",
        category: "chocolate",
        contact: "Yossi Levi",
        phone: "+32 2 891 0111",
        email: "sales@barry-callebaut.com",
        website: "https://www.barry-callebaut.com",
        country: "בלגיה",
        notes: "ספק גלובלי גדול. עיסת קקאו דרום אמריקה. נראה מבטיח.",
        status: "negotiation",
        createdAt: day(40),
        updatedAt: day(2),
      },
      {
        id: "sup_cargill",
        company: "Cargill Cocoa",
        category: "chocolate",
        contact: "Maria Gomez",
        phone: "+31 20 357 5000",
        email: "cocoa@cargill.com",
        website: "https://www.cargill.com",
        country: "הולנד",
        notes: "חמאת קקאו דיאודורייזד. מחיר תחרותי.",
        status: "quote_received",
        createdAt: day(35),
        updatedAt: day(5),
      },
      {
        id: "sup_tate",
        company: "Tate & Lyle",
        category: "supplements",
        contact: "David Cohen",
        phone: "+44 20 7257 2100",
        email: "allulose@tateandlyle.com",
        website: "https://www.tateandlyle.com",
        country: "בריטניה",
        notes: "אלולוז בטוהר גבוה. ממתין לדוגמה.",
        status: "sample_requested",
        createdAt: day(20),
        updatedAt: day(3),
      },
      {
        id: "sup_cemoi",
        company: "Cémoi",
        category: "chocolate",
        contact: "Pierre Dubois",
        phone: "+33 4 68 56 11 11",
        email: "contact@cemoi.com",
        website: "https://www.cemoi.fr",
        country: "צרפת",
        notes: "Single origin אקוודור. טעימה מעולה.",
        status: "sample_received",
        createdAt: day(18),
        updatedAt: day(1),
      },
      {
        id: "sup_lecico",
        company: "Lecico GmbH",
        category: "supplements",
        contact: "Hannah Weber",
        phone: "+49 4101 50 27 0",
        email: "info@lecico.de",
        website: "https://www.lecico.de",
        country: "גרמניה",
        notes: "לציטין חמנייה ללא GMO.",
        status: "contacted",
        createdAt: day(10),
        updatedAt: day(4),
      },
      {
        id: "sup_newco",
        company: "Andes Cacao Co.",
        category: "chocolate",
        contact: "Lucía Ramírez",
        phone: "+593 4 256 7890",
        email: "hello@andescacao.com",
        country: "אקוודור",
        notes: "ספק חדש מאקוודור. דרוש בירור.",
        status: "new",
        createdAt: day(3),
        updatedAt: day(3),
      },
      {
        id: "sup_chocoworld",
        company: "Chocolate World",
        category: "molds",
        contact: "Tom Janssen",
        phone: "+32 3 230 1234",
        email: "sales@chocolateworld.be",
        website: "https://www.chocolateworld.be",
        country: "בלגיה",
        notes: "מולדים (תבניות) לפוליקרבונט. קטלוג רחב.",
        status: "contacted",
        createdAt: day(12),
        updatedAt: day(6),
      },
      {
        id: "sup_cocoatown",
        company: "CocoaTown",
        category: "melanger",
        contact: "Raj Patel",
        phone: "+1 678 343 0211",
        email: "info@cocoatown.com",
        website: "https://www.cocoatown.com",
        country: "ארה\"ב",
        notes: "מכונות מלנגר (ECGC) לטחינת קקאו. ממתין להצעת מחיר.",
        status: "quote_received",
        createdAt: day(15),
        updatedAt: day(4),
      },
      {
        id: "sup_packline",
        company: "ULMA Packaging",
        category: "packaging",
        contact: "Iñaki Garcia",
        phone: "+34 943 73 92 00",
        email: "info@ulmapackaging.com",
        website: "https://www.ulmapackaging.com",
        country: "ספרד",
        notes: "מכונות אריזה (flow-pack) לחטיפי שוקולד.",
        status: "new",
        createdAt: day(5),
        updatedAt: day(5),
      },
    ],
    events: [
      {
        id: "ev1",
        supplierId: "sup_barry",
        type: "call",
        text: "שוחחתי עם יוסי. יש עיסת קקאו מדרום אמריקה. MOQ 25 קילו. ישלח COA. מעקב ביום שני.",
        date: day(2),
        createdAt: day(2),
      },
      {
        id: "ev2",
        supplierId: "sup_barry",
        type: "email",
        text: "התקבלה הצעת מחיר ראשונית: 9.2€/ק\"ג. מנהלים מו\"מ על MOQ.",
        date: day(6),
        createdAt: day(6),
      },
      {
        id: "ev3",
        supplierId: "sup_cemoi",
        type: "sample",
        text: "התקבלו דוגמאות Single Origin אקוודור. טעם פירותי, מרקם חלק.",
        date: day(1),
        createdAt: day(1),
      },
      {
        id: "ev4",
        supplierId: "sup_cargill",
        type: "quote",
        text: "הצעת מחיר לחמאת קקאו דיאודורייזד — 8.4€/ק\"ג, זמן אספקה 30 יום.",
        date: day(5),
        createdAt: day(5),
      },
    ],
    materials: [
      {
        id: "mat1",
        supplierId: "sup_barry",
        kind: "cocoa_mass",
        country: "אקוודור / פרו",
        variety: "Nacional",
        origin: "blend",
        productCode: "BC-CM-2201",
        moq: "25 ק\"ג",
        price: "9.2 €/ק\"ג",
        coa: true,
        score: 8,
        tasteNotes: "פירותי, חמיצות עדינה, גוף מלא",
        createdAt: day(6),
        updatedAt: day(2),
      },
      {
        id: "mat2",
        supplierId: "sup_cargill",
        kind: "cocoa_butter",
        country: "הולנד",
        deodorized: true,
        productCode: "CG-CB-DEO",
        moq: "50 ק\"ג",
        price: "8.4 €/ק\"ג",
        coa: true,
        score: 7,
        notes: "ריח ניטרלי, מתאים לתערובת",
        createdAt: day(5),
        updatedAt: day(5),
      },
      {
        id: "mat3",
        supplierId: "sup_tate",
        kind: "allulose",
        country: "בריטניה",
        purity: "≥ 98%",
        moq: "100 ק\"ג",
        price: "6.1 €/ק\"ג",
        coa: false,
        createdAt: day(8),
        updatedAt: day(3),
      },
      {
        id: "mat4",
        supplierId: "sup_lecico",
        kind: "lecithin",
        source: "sunflower",
        country: "גרמניה",
        moq: "20 ק\"ג",
        price: "4.3 €/ק\"ג",
        coa: true,
        createdAt: day(9),
        updatedAt: day(4),
      },
      {
        id: "mat5",
        supplierId: "sup_cemoi",
        kind: "cocoa_mass",
        country: "אקוודור",
        variety: "Arriba Nacional",
        origin: "single",
        productCode: "CM-ARR-72",
        moq: "30 ק\"ג",
        price: "10.8 €/ק\"ג",
        coa: true,
        score: 9,
        tasteNotes: "יסמין, פרי הדר, סיומת ארוכה",
        createdAt: day(2),
        updatedAt: day(1),
      },
    ],
    samples: [
      {
        id: "smp1",
        supplierId: "sup_cemoi",
        materialId: "mat5",
        date: day(1),
        material: "עיסת קקאו Single Origin אקוודור",
        impression: "מרשים מאוד, ארומה נקייה",
        taste: 9,
        texture: 9,
        melt: 8,
        aftertaste: "נקייה, מעט פרחונית",
        finalScore: 9,
        suitable: true,
        createdAt: day(1),
      },
      {
        id: "smp2",
        supplierId: "sup_barry",
        materialId: "mat1",
        date: day(4),
        material: "עיסת קקאו Blend דרום אמריקה",
        impression: "טוב, עקבי",
        taste: 8,
        texture: 8,
        melt: 7,
        aftertaste: "מעט מרירה",
        finalScore: 8,
        suitable: true,
        createdAt: day(4),
      },
    ],
    quotes: [
      {
        id: "q1",
        supplierId: "sup_barry",
        material: "עיסת קקאו Blend",
        pricePerKg: 9.2,
        moq: "25 ק\"ג",
        leadTime: "21 יום",
        paymentTerms: "שוטף +30",
        notes: "מחיר פתיחה, ניתן למו\"מ",
        date: day(6),
        createdAt: day(6),
      },
      {
        id: "q2",
        supplierId: "sup_cargill",
        material: "חמאת קקאו דיאודורייזד",
        pricePerKg: 8.4,
        moq: "50 ק\"ג",
        leadTime: "30 יום",
        paymentTerms: "שוטף +60",
        date: day(5),
        createdAt: day(5),
      },
      {
        id: "q3",
        supplierId: "sup_cemoi",
        material: "עיסת קקאו Single Origin",
        pricePerKg: 10.8,
        moq: "30 ק\"ג",
        leadTime: "28 יום",
        paymentTerms: "מקדמה 50%",
        date: day(1),
        createdAt: day(1),
      },
    ],
    tasks: [
      {
        id: "tk1",
        supplierId: "sup_barry",
        title: "מעקב ביום שני — לקבל COA",
        done: false,
        dueDate: day(-3),
        createdAt: day(2),
      },
      {
        id: "tk2",
        supplierId: "sup_tate",
        title: "לעקוב אחר דוגמת אלולוז",
        done: false,
        dueDate: day(-1),
        createdAt: day(3),
      },
      {
        id: "tk3",
        supplierId: "sup_cemoi",
        title: "להשוות מחירים מול Barry Callebaut",
        done: false,
        createdAt: day(1),
      },
      {
        id: "tk4",
        supplierId: "sup_lecico",
        title: "לבקש COA ללציטין חמנייה",
        done: true,
        createdAt: day(4),
      },
    ],
    files: [
      {
        id: "f1",
        supplierId: "sup_cargill",
        name: "Cargill_CocoaButter_COA.pdf",
        category: "coa",
        mime: "application/pdf",
        size: 248_000,
        createdAt: day(5),
      },
      {
        id: "f2",
        supplierId: "sup_barry",
        name: "BarryCallebaut_Quote_2026.pdf",
        category: "quote",
        mime: "application/pdf",
        size: 132_000,
        createdAt: day(6),
      },
      {
        id: "f3",
        supplierId: "sup_cemoi",
        name: "Cemoi_TDS_SingleOrigin.pdf",
        category: "tds",
        mime: "application/pdf",
        size: 410_000,
        createdAt: day(2),
      },
    ],
  };
}
