"use client";

import { useEffect, useState } from "react";

type Key = "energy" | "relax" | "sleep";
type Product = { key: Key; name: string; he: string; moment: string; line: string; color: string; pale: string; pack: string; lifestyle: string; ingredients: {name:string; amount:string; role:string}[] };

const A = "/claude-v29/";
const products: Record<Key, Product> = {
  energy: { key:"energy", name:"ENERGY", he:"להיכנס לקצב.", moment:"בוקר · להתחיל", line:"אנרגיה נקייה וממוקדת לרגע שבו היום צריך להתחיל לעבוד.", color:"#ed6d28", pale:"#fff1e8", pack:A+"claude-04-86638e6db8.webp", lifestyle:A+"claude-08-942c195fb5.jpg", ingredients:[{name:"מאקה",amount:"32%",role:"חיוניות ואנרגיה"},{name:"גוארנה",amount:"24%",role:"מיקוד מתמשך"},{name:"תה ירוק",amount:"20%",role:"ערנות מאוזנת"},{name:"ג׳ינסנג",amount:"16%",role:"תמיכה בביצועים"},{name:"ליקוריץ",amount:"8%",role:"איזון טבעי"}]},
  relax: { key:"relax", name:"RELAX", he:"להוריד הילוך.", moment:"מעבר · להירגע", line:"רגע שקט שמסמן לגוף שהיום יכול להתחיל להירגע.", color:"#687d36", pale:"#eff3e8", pack:A+"claude-05-b597c7330f.webp", lifestyle:A+"claude-09-7c4a5a1ffc.jpg", ingredients:[{name:"מליסה",amount:"32%",role:"תחושת רוגע"},{name:"פסיפלורה",amount:"24%",role:"איזון רגשי"},{name:"מאקה",amount:"20%",role:"חיוניות מאוזנת"},{name:"ולריאן",amount:"16%",role:"הרפיה טבעית"},{name:"ליקוריץ",amount:"8%",role:"טעם ואיזון"}]},
  sleep: { key:"sleep", name:"SLEEP", he:"לסגור את היום.", moment:"ערב · לישון", line:"ריטואל ערב שקט שהופך את המעבר לשינה לרגע שמחכים לו.", color:"#58719a", pale:"#edf2f8", pack:A+"claude-06-f5a2e95580.webp", lifestyle:A+"claude-11-0ea0852b44.jpg", ingredients:[{name:"מליסה",amount:"40%",role:"רוגע טבעי"},{name:"פסיפלורה",amount:"24%",role:"הרפיה"},{name:"ולריאן",amount:"20%",role:"תמיכה בשגרת ערב"},{name:"ליקוריץ",amount:"16%",role:"איזון וטעם"}]}
};
const keys: Key[]=["energy","relax","sleep"];

function Header({cart}:{cart:number}){
 const [open,setOpen]=useState(false);
 return <><div className="announce">משלוח חינם בקנייה מעל ₪249 · אלפי לקוחות מרוצים · מוקד שירות ישראלי</div><header><a className="logo" href="/"><img src={A+"claude-01-d3d4106af9.png"} alt="mood"/></a><nav className={open?"open":""}><a href="/#moments">המוצרים</a><a href="/#formula">הפורמולה</a><a href="/#chocolate">השוקולד</a><a href="/#story">הסיפור שלנו</a><a href="/#reviews">ביקורות</a></nav><div className="headActions"><a href="/cart">סל <b>{cart}</b></a><button onClick={()=>setOpen(!open)}>☰</button></div></header></>
}

function Home({add}:{add:(k:Key,q?:number)=>void}){
 const [active,setActive]=useState<Key>("energy"); const p=products[active];
 const [faces,setFaces]=useState(false); useEffect(()=>{const t=setInterval(()=>setFaces(x=>!x),4000);return()=>clearInterval(t)},[]);
 return <main>
  <section className="hero"><img src={A+"claude-02-198f3d5033.jpg"} alt="שוקולד mood"/><div className="shade"/><div className="heroText"><p className="kicker">ONE BITE · EVERYTHING CHANGES</p><h1>אל תבחרו מוצר.<br/>בחרו את הרגע.</h1><p>שוקולד מריר 70% לכל רגע ביום.<br/>ביס אחד — וההרגשה משתנה.</p><div><a className="btn white" href="#moments">לבחירת הרגע</a><a className="textLink" href="/energy">למארז היכרות ←</a></div></div><div className="heroStats"><span>★ 4.9</span><span>70% קקאו</span><span>30 ביסים</span></div></section>
  <div className="marquee"><div>70% שוקולד מריר · ללא תוספת סוכר · רכיבים טבעיים · פותח בישראל · כשר פרווה · 30 יחידות · ENERGY · RELAX · SLEEP · ריטואל, לא עוד תוסף ·</div></div>
  <section className="section moments" id="moments"><div className="sectionTitle"><p className="kicker dark">CHOOSE THE MOMENT</p><h2>הבחירה מתחילה בצורך.<br/>לא ברשימת רכיבים.</h2><p>שלושה רגעים. שלוש פורמולות. ריטואל אחד שקל להתמיד בו.</p></div><div className="cards">{keys.map(k=>{const x=products[k]; return <a href={`/${k}`} className="productCard" key={k} style={{"--c":x.color} as React.CSSProperties}><img className={faces?"show":""} src={x.lifestyle} alt={x.name}/><div className="cardClean"><img src={x.pack} alt={`מארז ${x.name}`}/></div><div className="cardShade"/><div className="cardCopy"><small>{x.moment}</small><h3>{x.he}</h3><p>{x.line}</p><span>בחרו מארז</span></div></a>})}</div></section>
  <section className="formula" id="formula" style={{"--c":p.color,"--p":p.pale} as React.CSSProperties}><div className="formulaVisual"><div className="orbit"><span>{p.name}</span><img src={p.pack} alt={`פורמולת ${p.name}`}/>{p.ingredients.slice(0,4).map((i,n)=><i key={i.name} className={`dot d${n}`}>{i.name}<b>{i.amount}</b></i>)}</div></div><div className="formulaCopy"><p className="kicker dark">FEWER INGREDIENTS. CLEAR PURPOSE.</p><h2>פחות רשימה.<br/>יותר כוונה.</h2><p>{p.line} כל רכיב נבחר סביב תפקיד ברור ובמינון קבוע בכל ביס.</p><div className="tabs">{keys.map(k=><button className={k===active?"active":""} onClick={()=>setActive(k)} key={k}>{products[k].name}</button>)}</div><div className="ingredients">{p.ingredients.map((i,n)=><div key={i.name}><b>0{n+1}</b><strong>{i.name}</strong><span>{i.role}</span><em>{i.amount}</em></div>)}</div><a className="btn darkBtn" href={`/${p.key}`}>לגלות את {p.name}</a></div></section>
  <section className="chocolate" id="chocolate"><img src={A+"claude-03-6a6dde2a7c.jpg"} alt="רונן אפללו, השוקולטייר של mood"/><div><p className="kicker">THE CHOCOLATE</p><h2>קודם כול,<br/>שוקולד אמיתי.</h2><p>הפורמולה משנה איך מרגישים. השוקולד גורם לרצות עוד ביס. שוקולד מריר 70% שפותח עם רונן אפללו, אלוף עולם בשוקולד 2022.</p><div className="metrics"><b>70%<small>קקאו</small></b><b>49×24×5<small>מ״מ · ביס מדוד</small></b><b>30<small>יחידות במארז</small></b></div><a className="textLink lightLink" href="/energy">לטעום את ההבדל ←</a></div></section>
  <section className="story" id="story"><div><p className="kicker dark">A NOTE FROM THE FOUNDERS</p><h2>רצינו הרגל<br/>שבאמת רוצים לשמור.</h2><p>לא עוד קפסולה שמחכים לסיים. לא עוד מוצר שנשכח במגירה. בנינו ריטואל קטן, מדויק וטעים — כזה שנכנס לחיים במקום להפריע להם.</p><p className="signature">נדב ומתיאס<br/><small>מייסדי mood</small></p></div><img src={A+"claude-07-b7da002ce1.jpg"} alt="מייסדי mood"/></section>
  <section className="section reviews" id="reviews"><div className="sectionTitle"><p className="kicker dark">REAL PEOPLE · REAL RITUALS</p><h2>רגעים אמיתיים.<br/>בתוך ימים אמיתיים.</h2><p>לא תמונת סטוק של “בריאות”. אנשים שמצאו רגע קטן שעובד בשבילם.</p></div><div className="reviewPhotos">{[["claude-08-942c195fb5.jpg","יעל","ENERGY · רגע לפני היום"],["claude-09-7c4a5a1ffc.jpg","נועה","RELAX · רגע בין הילדים"],["claude-10-d1ba1a00f5.jpg","מיה","RELAX · רגע של אור"],["claude-11-0ea0852b44.jpg","שירה","SLEEP · לפני השינה"],["claude-12-74a9617b37.jpg","טלי","SLEEP · טקס הלילה"]].map(x=><figure key={x[1]}><img src={A+x[0]} alt={x[1]}/><figcaption><b>{x[1]}</b><span>{x[2]}</span></figcaption></figure>)}</div><div className="reviewQuotes">{["החליף לי את הקפה השני. סוף סוף משהו שאני באמת מחכה לו.","הטעם מרגיש כמו שוקולד פרימיום, לא כמו עוד משימה בריאותית.","ביס קטן שמסמן לי שהעבודה נגמרה והערב מתחיל.","האריזה יפה, הטעם מדויק והכי חשוב — קל להתמיד.","זה נכנס לשגרה שלי מהר יותר מכל תוסף שניסיתי."].map((q,i)=><article key={q}><div>★★★★★</div><p>“{q}”</p><small>{["יעל","נועה","מיה","שירה","טלי"][i]} · רכישה מאומתת</small></article>)}</div></section>
  <section className="faq"><p className="kicker dark">GOOD TO KNOW</p><h2>שאלות שאולי נשארו.</h2>{["איך בוחרים בין ENERGY, RELAX ו־SLEEP?","מתי אוכלים את השוקולד?","כמה ביסים יש בכל מארז?","זה שוקולד או תוסף תזונה?","האם המוצרים כשרים?"].map((q,i)=><details key={q}><summary>{q}<span>+</span></summary><p>{["מתחילים מהרגע שרוצים לשנות: ENERGY לבוקר, RELAX למעבר מהיום לערב, ו־SLEEP לפני השינה.","יחידה אחת ביום, בזמן שמתאים לריטואל שבחרתם.","30 יחידות אישיות ומדודות בכל מארז.","זה שוקולד פונקציונלי: שוקולד מריר אמיתי עם פורמולה ממוקדת.","כן. המוצרים כשרים פרווה."][i]}</p></details>)}</section>
  <section className="club"><p className="kicker">THE MOOD CLUB</p><h2>ריטואל טוב<br/>לא צריך לזכור להזמין.</h2><p>משלוח קבוע, מחיר טוב יותר וגמישות מלאה. מדלגים או מבטלים בכל רגע.</p><a className="btn white" href="/energy">להצטרף למועדון</a></section>
 </main>
}

function ProductPage({p,add}:{p:Product;add:(k:Key,q?:number)=>void}){
 const [tier,setTier]=useState(1); const [added,setAdded]=useState(false); const tiers=[{q:1,n:"מארז היכרות",price:189},{q:2,n:"מארז זוגי",price:339},{q:3,n:"מארז התמדה",price:459}]; const t=tiers[tier];
 const act=()=>{add(p.key,t.q);setAdded(true);setTimeout(()=>setAdded(false),1400)};
 return <main style={{"--c":p.color,"--p":p.pale} as React.CSSProperties}>
  <section className="pdpHero"><div className="pdpVisual"><img className="person" src={p.lifestyle} alt={p.name}/><img className="pack" src={p.pack} alt={`מארז ${p.name}`}/></div><div className="buy"><p className="kicker dark">{p.moment}</p><h1>{p.name}</h1><div className="stars">★★★★★ <a href="#pReviews">4.9 · 127 ביקורות</a></div><h2>{p.he}</h2><p>{p.line}</p><div className="proofPills"><span>70% קקאו</span><span>30 יחידות</span><span>ללא תוספת סוכר</span></div><h3>בחרו את הריטואל שלכם</h3><div className="tiers">{tiers.map((x,i)=><button onClick={()=>setTier(i)} className={tier===i?"active":""} key={x.n}>{i===2&&<em>הכי משתלם</em>}<i></i><strong>{x.n}</strong><span>{x.q*30} ביסים</span><b>₪{x.price}</b></button>)}</div><button className="add" onClick={act}>{added?"נוסף לסל ✓":`הוסיפו לסל · ₪${t.price}`}</button><small className="assure">משלוח מהיר · רכישה מאובטחת · אפשרות לביטול</small></div></section>
  <section className="pdpWhy"><div><p className="kicker dark">WHY {p.name}</p><h2>ביס אחד.<br/>תפקיד אחד ברור.</h2></div><p>{p.line} לא עוד רשימה ארוכה של הבטחות — אלא פורמולה קצרה בתוך שוקולד שבאמת רוצים לאכול.</p></section>
  <section className="pdpFormula"><div className="formulaDisc"><img src={p.pack} alt={p.name}/>{p.ingredients.slice(0,4).map((i,n)=><span className={`f${n}`} key={i.name}><b>{i.name}</b>{i.amount}</span>)}</div><div><p className="kicker dark">WHAT'S INSIDE</p><h2>פורמולה קצרה.<br/>כוונה ברורה.</h2><p>כל רכיב נבחר סביב הרגע של {p.name}, במינון קבוע בכל ביס.</p><div className="ingredients">{p.ingredients.map((i,n)=><div key={i.name}><b>0{n+1}</b><strong>{i.name}</strong><span>{i.role}</span><em>{i.amount}</em></div>)}</div></div></section>
  <section className="taste"><img src={A+"claude-02-198f3d5033.jpg"} alt="שוקולד mood"/><div><p className="kicker">70% DARK CHOCOLATE</p><h2>זה צריך לעבוד.<br/>הטעם לא פחות חשוב.</h2><p>שוקולד מריר אמיתי, מרקם נקי וביס בגודל מדויק. כי הרגל טוב נבנה ממשהו שמחכים לו — לא ממשהו שמכריחים את עצמנו לקחת.</p><ul><li>שוקולד מריר 70%</li><li>30 יחידות אישיות</li><li>פותח ומיוצר בישראל</li></ul></div></section>
  <section className="section reviews" id="pReviews"><div className="sectionTitle"><p className="kicker dark">4.9 / 5 · VERIFIED BUYERS</p><h2>הם הכניסו את הרגע<br/>לתוך היום.</h2></div><div className="reviewQuotes">{["הטעם הפתיע אותי. מרגיש כמו פינוק ולא כמו תוסף.","אחרי שבוע זה כבר היה חלק קבוע מהיום שלי.","קטן, מדויק ונוח — ובעיקר ממש טעים."].map((q,i)=><article key={q}><div>★★★★★</div><p>“{q}”</p><small>{["רוני","איתי","דנה"][i]} · רכישה מאומתת</small></article>)}</div></section>
  <section className="cross"><p className="kicker dark">ANOTHER MOMENT?</p><h2>אולי היום צריך משהו אחר.</h2><div>{keys.filter(k=>k!==p.key).map(k=><a href={`/${k}`} key={k}><img src={products[k].pack}/><b>{products[k].name}</b><span>{products[k].he}</span></a>)}</div></section>
 </main>
}

function Footer(){return <footer><img src={A+"claude-01-d3d4106af9.png"} alt="mood"/><p>שוקולד פונקציונלי לרגעים אמיתיים.</p><div><a href="/energy">ENERGY</a><a href="/relax">RELAX</a><a href="/sleep">SLEEP</a><a href="/terms">תקנון</a><a href="/privacy">פרטיות</a><a href="/accessibility">נגישות</a></div><small>© 2026 mood ritual chocolate</small></footer>}

export default function Storefront({route}:{route:string}){const [cart,setCart]=useState(0);const add=(_:Key,q=1)=>setCart(v=>v+q); const product=products[route as Key]; return <div dir="rtl"><Header cart={cart}/>{product?<ProductPage p={product} add={add}/>:route==="home"?<Home add={add}/>:<main className="legal"><h1>{route==="privacy"?"מדיניות פרטיות":route==="accessibility"?"הצהרת נגישות":route==="cart"?"הסל שלכם":"תקנון האתר"}</h1><p>עמוד זה מוצג בתצוגת ההדגמה. החיבור המלא למדיניות, לתשלומים ולמערכת Shopify יבוצע בשלב ההטמעה.</p><a className="btn darkBtn" href="/">חזרה לאתר</a></main>}<Footer/></div>}
