/**
 * Hebrew headline bank — curated per state.
 *
 * These are the offline fallback. Style notes:
 *  - dry, observed Hebrew (not literary, not motivational)
 *  - no exclamation marks
 *  - 4–9 words for primary, 3–6 for secondary
 *  - no product mention, no slogan language
 */

export const HEADLINES_HE: Record<string, { primary: string; secondary: string | null }> = {
  'afternoon-crash':           { primary: 'הגוף ליד השולחן. הראש כבר לא.', secondary: 'אחר צהריים, יום שלישי' },
  'third-coffee':              { primary: 'זה כבר לא בגלל הקפה.', secondary: 'זה בגלל הריטואל' },
  'startup-burnout':           { primary: 'השאפתנות הלכה לישון. הדק עוד פתוח.', secondary: 'אחרי חצות' },
  'pre-workout-hesitation':    { primary: 'הגוף הגיע. הראש עוד לא הסכים.', secondary: 'חניית החדר כושר' },
  'doomscroll-fatigue':        { primary: 'האגודל עייף. המוח עייף יותר.', secondary: 'אף אחד מהם לא עוצר' },
  'unread-messages-anxiety':   { primary: 'הטלפון הפוך, היום עוד לא התחיל.', secondary: 'הימנעות בשפת הרגיעה' },
  'mentally-absent':           { primary: 'מחייכים כאן. כבר במקום אחר.', secondary: null },
  'social-exhaustion':         { primary: 'המסיבה ממשיכה. הם כבר בבית בראש.', secondary: null },
  'airport-fatigue':           { primary: 'שלושה אזורי זמן בגוף אחד.', secondary: 'אף אחד מהם לא נח' },
  'zombie-mode':               { primary: 'עושים. צופים בעצמם עושים.', secondary: null },
  'low-battery-feeling':       { primary: 'הטלפון על ארבעה אחוז. גם הם.', secondary: null },
  'too-many-tabs':             { primary: 'עשרים ושלושה טאבים פתוחים. אף אחד מהם המשימה.', secondary: 'עסוקים כדי לא להיות פנויים' },
  'post-lunch-collapse':       { primary: 'המזלג נח. הפגישה הבאה ב-14:22.', secondary: null },
  'creative-paralysis':        { primary: 'הסמן מהבהב ארבעים דקות. גם הם.', secondary: null },
  'before-meeting-panic':      { primary: 'חוזרים על המילים, שלוש דקות לפני שיראו אותם.', secondary: null },
  'exhausted-parenting':       { primary: 'התיישבו לשנייה. נכנסו בטעות לתוך יום רביעי.', secondary: null },
  'emotional-overload':        { primary: 'בוכים בשקט מספיק שאף אחד לא ישאל.', secondary: null },
  'exhausted-commute':         { primary: 'החלון רואה במקומם.', secondary: 'אוטובוס 18:42' },
  'sunday-anxiety':            { primary: 'יום ראשון בערב. השבוע כבר התחיל בלי רשות.', secondary: null },
  'mentally-offline':          { primary: 'מהנהנים לדברים שלא שמעו.', secondary: null },
  'tired-but-continuing':      { primary: 'בלי אוויר שני. ממשיכים.', secondary: null },
  'overstimulated-brain':      { primary: 'הכול רועש. גם השקט רועש.', secondary: null },
  'no-motivation-morning':     { primary: 'המיטה היא הוויכוח היחיד שמפסידים בו.', secondary: null },
  'fake-productivity':         { primary: 'מקלידים מהר על כלום מסוים.', secondary: null },
  'body-awake-mind-asleep':    { primary: 'כבר במקלחת. הראש יגיע לקראת תשע.', secondary: null },
  'exhausted-scrolling':       { primary: '23:51. מחר כבר התחיל.', secondary: null },
  'dead-eyed-work-mode':       { primary: 'ההשתקפות במסך הפסיקה להעמיד פנים.', secondary: null },
  'mentally-disconnected':     { primary: 'כן. כן. כן. — אף אחד מהם לא נשמע.', secondary: null },
  'overwhelmed-founder':       { primary: 'ארבעים ואחד שרשורים. אדם אחד אחראי.', secondary: null },
  'tab-switching-paralysis':   { primary: 'שישה מעברים בעשר שניות. אפס התקדמות.', secondary: null },
  'gym-avoidance':             { primary: 'תשע דקות בחניה. עוד לא כיבו מנוע.', secondary: null },
  'emotional-numbness':        { primary: 'העוגה מולם. גם כולם. שום דבר לא נוחת.', secondary: null },
  'restless-work-energy':      { primary: 'רגל קופצת, עט נוקש, מייל בלי סיבה.', secondary: 'אף אחד מהם המשימה' },
  'late-afternoon-collapse':   { primary: '17:22. הגוף הגיש בקשת פרישה מוקדמת.', secondary: null },
  'exhausted-creativity':      { primary: 'הדף ריק. גם המקור.', secondary: null },
  'forced-productivity':       { primary: 'ממשיכים כי להפסיק כבר יותר מפחיד.', secondary: null },
  'caffeine-no-longer-works':  { primary: 'הכוס ריקה. היציבה אותה יציבה.', secondary: null },
  'attention-fragmentation':   { primary: 'שלוש מחשבות התחילו. אף אחת לא נגמרה.', secondary: 'כבר ברביעית' },
  'low-social-battery':        { primary: 'מקשיבים שלוש שעות. נגמר להם.', secondary: null },
  'constant-notifications':    { primary: 'הטלפון רוטט. היד מגיעה. העיניים לא.', secondary: null },
  'decision-fatigue':          { primary: 'שתים-עשרה אפשרויות על המדף. אפס בסל.', secondary: null },
  'mentally-checked-out':      { primary: 'בשיחה. בהשתקה. בכוכב אחר.', secondary: null },
  'emotional-static':          { primary: 'לא עצוב. לא בסדר. שום דבר שיש לו מילה.', secondary: null },
  'workday-blur':              { primary: 'שלישי וחמישי התאחדו. אף אחד לא חתם על זה.', secondary: null },
  'quiet-panic':               { primary: 'מחייכים בפגישה. החזה עושה משהו אחר.', secondary: null },
  'overstimulated-office':     { primary: 'אוזניות עליהן. מוזיקה כבויה.', secondary: 'רק קיר' },
  'overwhelmed-student':       { primary: 'שלושה מרקרים נפלו על אותו עמוד.', secondary: 'העמוד ניצח' },
  'mentally-overloaded':       { primary: 'יותר מדי בראש. כולם מחזיקים את הדלת.', secondary: null },
  'tired-ambition':            { primary: 'עוד דוחפים. שקט יותר משנה שעברה.', secondary: null },
  'endless-task-feeling':      { primary: 'ניקו את התיבה. התיבה התמלאה בזמן הניקוי.', secondary: null },
  'impossible-focus':          { primary: 'קוראים שוב את אותו משפט. הוא עדיין לא נוחת.', secondary: null },
  'slow-brain-morning':        { primary: 'הגוף קם. המוח ביקש עוד עשר דקות ושכח.', secondary: null },
  'emotionally-drained':       { primary: 'יושבים ברכב. מנוע כבוי. מפתח עוד בפנים.', secondary: null },
  'mentally-somewhere-else':   { primary: 'בארוחה כאן. בפגישה מיום שלישי בראש.', secondary: null },
  'exhausted-but-wired':       { primary: '01:34. גוף כבד, מוח עוד צועד.', secondary: null },
  'pressure-fatigue':          { primary: 'נושאים את היום בידיים שכבר התרגלו.', secondary: null },
  'overconnected-exhaustion':  { primary: 'זמינים לארבעים ושלושה. לא זמינים לעצמם.', secondary: null },
  'performance-fatigue':       { primary: 'מחזיקים את התנוחה בין הדלת לחדר.', secondary: null },
  'modern-brain-overload':     { primary: 'יותר מדי טאבים. כולל אלה שלא על המסך.', secondary: null },
};
