/**
 * GET /api/mvp/share?token=… — public read-only kit view (roadmap #25)
 *
 * Deliberately session-free: the share token is a random 32-char
 * secret generated per generation. The response contains ONLY kit
 * content — no tenant ids, no operator ids, no emails.
 */

import { NextResponse, type NextRequest } from 'next/server';
import { createMvpGenerationMemoryStore } from '@lib/mvpGenerationMemory';

export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';

export async function GET(req: NextRequest): Promise<NextResponse> {
  const token = new URL(req.url).searchParams.get('token');
  if (!token || token.length < 16) {
    return NextResponse.json({ error: 'token is required' }, { status: 400 });
  }

  const state = await createMvpGenerationMemoryStore().read();
  const generation = state.records.find(
    (r) => r.shareToken === token && r.status === 'ready',
  );
  if (!generation) {
    return NextResponse.json({ error: 'kit not found' }, { status: 404 });
  }

  // Content only — strip every identifier except the kit itself.
  return NextResponse.json({
    kit: {
      oneLinerCandidates: generation.oneLinerCandidates.map((o) => ({ text: o.text })),
      hooks: generation.hooks.map((h) => ({
        text: h.text, audience: h.audience,
        situation: h.situation, visualDirection: h.visualDirection,
      })),
      ugcScripts: generation.ugcScripts.map((u) => ({
        title: u.title, durationSec: u.durationSec,
        script: u.scriptHebrew, shotList: u.shotList, cta: u.callToActionHebrew,
      })),
      imageConcepts: generation.imageConcepts.map((c) => ({
        title: c.title, visualDescription: c.visualDescription,
      })),
      verticalId: generation.verticalId ?? null,
      generatedAt: generation.completedAt ?? generation.createdAt,
    },
    advisoryNotice: 'Shared creative kit · generated by MOOD Creative OS.',
  });
}
